package p000;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes2.dex */
enum ejs {
    IDLE,
    SHOW_ROLL_LEFT,
    SHOW_ROLL_RIGHT,
    SHOW_ARROW_RIGHT,
    SHOW_ARROW_LEFT,
    SHOW_ARROW_UP,
    SHOW_ARROW_DOWN,
    SHOW_ARROW_BACKTRACK,
    SHOW_START_ARROW_LEFT,
    SHOW_START_ARROW_RIGHT,
    SHOW_WARNING_VELOCITY
}
