package p000;

import android.content.ComponentName;
import androidx.wear.widget.iZcI.hiCTUJiAxf;
import com.google.android.apps.camera.jni.tracking.yRU.CswIK;
import com.google.android.material.behavior.iWN.zuAgeeF;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes.dex */
public final class hgu {

    /* JADX INFO: renamed from: a */
    public static final ComponentName f27747a = new ComponentName("com.groupme.android", "com.groupme.android.sharing.SharingActivity");

    /* JADX INFO: renamed from: b */
    public static final ComponentName f27748b = new ComponentName("org.thoughtcrime.securesms", "org.thoughtcrime.securesms.ShareActivity");

    /* JADX INFO: renamed from: c */
    public static final mxk f27749c = mxk.m17136H("com.google.android.apps.messaging");

    /* JADX INFO: renamed from: d */
    public static final mxk f27750d = mxk.m17141M("com.facebook.mlite/com.facebook.mlite.share.view.ShareActivity", "com.facebook.orca/com.facebook.messenger.intents.ShareIntentHandler", "com.facebook.katana/com.facebook.inspiration.shortcut.shareintent.InpirationCameraShareDefaultAlias/com.facebook.inspiration.shortcut.shareintent.InpirationCameraShareTestAliasActionClarify/com.facebook.inspiration.platformsharing.activity.InpirationCameraShareDefaultAlias", "com.google.android.apps.messaging/com.google.android.apps.messaging.ui.conversationlist.ShareIntentActivity", "com.google.android.apps.tachyon/com.google.android.apps.tachyon.clips.share.ReceiveShareIntentActivity", "com.instagram.android/com.instagram.share.handleractivity.StoryShareHandlerActivity", "com.kakao.talk/com.kakao.talk.activity.SplashConnectActivity", "jp.naver.line.android/jp.naver.line.android.activity.selectchat.SelectChatActivityLaunchActivity/com.linecorp.line.share.common.view.FullPickerLaunchActivity", "com.snapchat.android/com.snap.mushroom.MainActivity", "org.telegram.messenger/org.telegram.ui.LaunchActivity", "com.viber.voip/com.viber.voip.WelcomeShareActivity", "com.tencent.mm/com.tencent.mm.ui.tools.ShareImgUI", "com.whatsapp/com.whatsapp.ContactPicker/com.whatsapp.contact.picker.ContactPicker", "com.groupme.android/com.groupme.android.sharing.SharingActivity", "kik.android/kik.android.chat.activity.KikPlatformLanding", "com.skype.raider/com.skype4life.MainActivity", "com.discord/com.discord.app.AppActivity$AppAction", "org.thoughtcrime.securesms/org.thoughtcrime.securesms.ShareActivity/org.thoughtcrime.securesms.sharing.ShareActivity/org.thoughtcrime.securesms.sharing.v2.ShareActivity", "com.imo.android.imoim/com.imo.android.imoim.activities.SharingActivity/com.imo.android.imoim.globalshare.SharingActivity2", hiCTUJiAxf.FOfgVFIDvlqg, "app.buzz.share/com.ss.android.buzz.proxy.MediaIntentReceiveActivity", "com.verizon.messaging.vzmsgs/com.verizon.mms.ui.LaunchConversationActivity", "com.textra/com.mplus.lib.ui.integration.IntegrationActivity", "com.twitter.android/com.twitter.composer.ComposerActivity", "com.google.android.talk/com.google.android.apps.hangouts.phone.ShareIntentActivity", "com.google.android.apps.dynamite/com.google.android.apps.dynamite.activity.main.MainActivity/com.google.android.apps.dynamite.PeopleActivityAlias/com.google.android.apps.dynamite.DynamiteDeepLink", "com.Slack/com.Slack.ui.UploadActivity", "com.vsco.cam/com.vsco.cam.navigation.LithiumActivity", "com.facebook.lite/com.facebook.lite.stories.activities.ShareToFbStoriesAlias", "com.google.android.apps.googlevoice/com.google.android.apps.voice.home.androidintents.AndroidIntentActivity");

    /* JADX INFO: renamed from: e */
    public static final mxk f27751e = mxk.m17141M("com.facebook.orca/com.facebook.messenger.intents.ShareIntentHandler", "com.facebook.katana/com.facebook.inspiration.shortcut.shareintent.InpirationCameraShareDefaultAlias/com.facebook.inspiration.platformsharing.activity.InpirationCameraShareDefaultAlias", "com.google.android.apps.messaging/com.google.android.apps.messaging.ui.conversationlist.VideoShareIntentActivity", "com.google.android.apps.tachyon/com.google.android.apps.tachyon.clips.share.ReceiveShareIntentActivity", "com.instagram.android/com.instagram.share.handleractivity.StoryShareHandlerActivity", "com.kakao.talk/com.kakao.talk.activity.SplashConnectActivity", "jp.naver.line.android/jp.naver.line.android.activity.selectchat.SelectChatActivityLaunchActivity/com.linecorp.line.share.common.view.FullPickerLaunchActivity", "com.snapchat.android/com.snap.mushroom.MainActivity", "org.telegram.messenger/org.telegram.ui.LaunchActivity", "com.viber.voip/com.viber.voip.WelcomeShareActivity", "com.tencent.mm/com.tencent.mm.ui.tools.ShareImgUI", "com.whatsapp/com.whatsapp.ContactPicker/com.whatsapp.contact.picker.ContactPicker", "com.groupme.android/com.groupme.android.sharing.SharingActivity", "kik.android/kik.android.chat.activity.KikPlatformLanding", "com.skype.raider/com.skype4life.MainActivity", "com.discord/com.discord.app.AppActivity$AppAction", CswIK.NjSlgjHjmq, "com.imo.android.imoim/com.imo.android.imoim.globalshare.SharingActivity2", "in.mohalla.sharechat/in.mohalla.sharechat.home.main.HomeActivity", "app.buzz.share/com.ss.android.buzz.proxy.MediaIntentReceiveActivity", "com.verizon.messaging.vzmsgs/com.verizon.mms.ui.LaunchConversationActivity", "com.textra/com.mplus.lib.ui.integration.IntegrationActivity", "com.twitter.android/com.twitter.composer.ComposerActivity", "com.google.android.talk/com.google.android.apps.hangouts.phone.VideoShareIntentActivity", "com.google.android.apps.dynamite/com.google.android.apps.dynamite.PeopleActivityAlias/com.google.android.apps.dynamite.DynamiteDeepLink", "com.Slack/com.Slack.ui.UploadActivity", "com.vsco.cam/com.vsco.cam.navigation.LithiumActivity", "com.google.android.youtube/com.google.android.youtube.UploadIntentHandlingActivity/com.google.android.apps.youtube.app.application.Shell_UploadActivity", "com.facebook.lite/com.facebook.lite.stories.activities.ShareToFbStoriesAlias");

    /* JADX INFO: renamed from: f */
    public static final mxk f27752f = mxk.m17141M("com.whatsapp", "com.facebook.orca", zuAgeeF.BZHDzanFrTwUa, "com.facebook.katana", "com.facebook.lite", "com.snapchat.android", "com.facebook.mlite", "org.telegram.messenger", "app.buzz.share", "com.twitter.android", "com.imo.android.imoim", "com.google.android.youtube", "in.mohalla.sharechat", "com.discord", "com.viber.voip", "com.google.android.apps.tachyon", "com.skype.raider", "jp.naver.line.android", "com.google.android.apps.dynamite", "com.google.android.talk", "com.google.android.apps.messaging", "com.vsco.cam", "com.tencent.mm", "com.Slack", "com.kakao.talk", "org.thoughtcrime.securesms", "kik.android", "com.groupme.android", "com.google.android.apps.googlevoice", "com.verizon.messaging.vzmsgs", "com.textra");
}
