package p000;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes.dex */
public enum lvi {
    UNKNOWN_AIRLOCK_FILE_STATE,
    ENTERING_AIRLOCK,
    IN_AIRLOCK,
    FAILED_TO_ENTER_AIRLOCK,
    FILES_DELETION_IN_PROGRESS,
    FILES_DELETED_FROM_AIRLOCK,
    FAILED_TO_DELETE_FROM_AIRLOCK
}
