#!/usr/bin/env python3
"""Checkpoint 126: unbox precise thumbnail dimensions generated by native reset."""
import os,struct
from pathlib import Path
from capstone import Cs,CS_ARCH_ARM64,CS_MODE_LITTLE_ENDIAN
from elftools.elf.elffile import ELFFile
track=os.environ["TRACK"];src=Path("liblightcycle.so").read_bytes()
with open("liblightcycle.so","rb") as f:
 e=ELFFile(f)
 seg=[(int(p["p_vaddr"]),int(p["p_vaddr"]+p["p_filesz"]),int(p["p_offset"]),int(p["p_flags"])) for p in e.iter_segments() if p["p_type"]=="PT_LOAD"]
 if track=="symbol-jni":
  for sec in e.iter_sections():
   if not hasattr(sec,"iter_symbols"):continue
   for sym in sec.iter_symbols():
    n=sym.name
    if any(x in n for x in ["ResetForPhotoSphereCapture","ResetForHorizontalCapture","InitPhoto","LightCycleNative","photoSphere"]):
     if "LightCycleNative" in n and not any(t in n for t in ("Reset","Init","AddImage")):continue
     print("NATIVE_SYMBOL",hex(int(sym["st_value"])),hex(int(sym["st_size"])),n)
def off(a):
 for lo,hi,ofs,fl in seg:
  if lo<=a<hi:return ofs+a-lo
 raise ValueError(hex(a))
cs=Cs(CS_ARCH_ARM64,CS_MODE_LITTLE_ENDIAN)
def dump(a,b):
 print("=== ASM",hex(a),hex(b))
 for z in cs.disasm(src[off(a):off(b-4)+4],a):
  print(f"{z.address:08x}: {z.mnemonic:10} {z.op_str}")
if track=="packed-params":
 for a,b in [(0x1188b8,0x118b80),(0xed84c,0xed928),(0x10f0fc,0x10f240)]:
  dump(a,b)
elif track=="symbol-jni":
 for a,b in [(0x1188b8,0x118ad0),(0xed84c,0xed928)]:
  dump(a,b)
else:raise SystemExit(track)
