plugins {
    id 'com.android.application'
}

android {
    namespace 'com.persie.spleeteraudit'
    compileSdk 35

    defaultConfig {
        applicationId 'com.persie.spleeteraudit'
        minSdk 26
        targetSdk 31
        versionCode 1
        versionName '1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    androidResources {
        noCompress += ['bin', 'tflite']
    }
}

dependencies {
    implementation files('libs/ttvspleeter.aar')
    implementation 'org.tensorflow:tensorflow-lite:2.14.0'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.14.0'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
